### ISSUE TITLE
Compatibility with tus 1.0

### ISSUE THREAD

**Issue by Acconut** [leblanc-simon/php-tus#1]
tus 1.0 is just around the corner. I would be pleased to see this implementation being updated to support the next version. Most updates are outside the core so only minimal changes are required to maintain comparability. You can find detailed information or get feedback at the according issue tus/tus-resumable-upload-protocol#57-

**Comment by hpvd** [comment]
would be really awesome to have compatibility with tus v1.0 also for php!

**Comment by leblanc-simon** [comment]
See https://github.com/ankitpokhrel/tus-php for tus protocol 1.0.0
