### ISSUE TITLE
Compatibility with tus-jquery-client 

### ISSUE THREAD

**Issue by daimoc** [leblanc-simon/php-tus#2]
Server.php is not working with a simple tus client based on tus-jquey-client.
The head request failed on getUserUuid function du to ajax jquery "cache buster".
By default ajax jquery request are generated with a random suffix query parameter to disable web cache response. Head requet is : 
- http://127.0.0.1/files/6f22be670ff31d075e40e642e9d9a0499def09e61930e2af7ff54f005ad32dfc?_=1424687992587

In getUserUuid fonction : $uuid = $this->getRequest()->getRequestUri() take the full request string including the random suffix, So this Uuid never exist in the redis table.
I don't know if there is a solution using Symphony framework, but a simple hack in pure PHP to remove suffix can be : 

``` PHP
private function getUserUuid()
    {
        if ($this->uuid === null) {
            $uuid = $this->getRequest()->getRequestUri();
            if (strpos($uuid,"?") !== false )
                $uuid = substr($uuid,0,strpos($uuid,"?"));
            if (strpos($uuid, $this->path) !== 0) {
                throw new \InvalidArgumentException('The uuid and the path doesn\'t match : '.$uuid.' - '.$this->path);
            }
            $this->uuid = $uuid;
        }
        return $this->uuid;
    }
```

**Comment by leblanc-simon** [comment]
See https://github.com/ankitpokhrel/tus-php for the next
