### ISSUE TITLE
Class not found issue

### ISSUE THREAD

**Issue by bhumin19** [leblanc-simon/php-tus#3]
i write below code to create instance of Client class...

require_once('PhpTus/Client.php');
$client = new PhpTus\Client();

but i got fatal error... "Class 'PhpTus\Client' not found"

i also tried with 
$client = new PhpTus\Client();

and it gave me same error. 

Is there any solution for that? or i need to use some framework to get it work?

**Comment by leblanc-simon** [comment]
- don't use `require_once('PhpTus/Client.php');` use composer to install vendor and `require_once 'vendor/autoload.php';`
- use `$client = new \PhpTus\Client();`
